<?php
/**
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title><?php echo $cedente; ?></title>
    <style type="text/css">
        /* Embed the CSS content here */
        <?php include $resource_path . '/css/styles.css' ?>
    </style>
</head>
<body>

    <div class="page">
        <div class="noprint info">
            <h2>Instruções de Impressão</h2>
            <ul>
                <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
                <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
                <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
            </ul>
            <span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
            <?php if ($valor_documento) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
            <?php if ($pagamento_minimo) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
            <br />
            <div class="linha-pontilhada margem-b20">Recibo do pagador</div>
        </div>

        <div class="info-empresa">
            <?php if ($logotipo) : ?>
            <div class="logo-empresa">
                <img alt="logotipo" src="<?php echo $logotipo; ?>" />
            </div>
            <?php endif ?>
        </div>
        <br />

        <div class="boleto-header">
            <div class="leftcontainer">
                <img src="<?= $logo_banco; ?>" alt="logotipo do banco" />
                <span class="codbanco"><?= $codigo_banco_com_dv ?></span>
            </div>
            <div class="rightcontainer">
                <span class="linha-digitavel"><?= $linha_digitavel ?></span>
            </div>
        </div>
        <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
            <tbody>
            <tr>
                <td colspan="4">
                    <span class="titulo">Pagador</span>
                    <span class="conteudo"><?php echo $sacado ?></span>
                </td>
                <td width="26%">
                    <span class="titulo">CPF/CNPJ do Pagador</span>
                    <span class="conteudo direita"><?php echo $sacado_documento ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Nosso Número</span>
                    <span class="conteudo"><?php echo $nosso_numero ?></span>
                </td>
                <td>
                    <span class="titulo">Nr. Documento</span>
                    <span class="conteudo"><?php echo $numero_documento ?></span>
                </td>
                <td colspan="2">
                    <span class="titulo">Agência/Código do Beneficiário</span>
                    <span class="conteudo"><?php echo $agencia_codigo_cedente ?></span>
                </td>
                <td class="caixa-gray-bg">
                    <span class="titulo">Vencimento</span>
                    <span class="conteudo direita"><?php echo $data_vencimento ?></span>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <span class="titulo">Beneficiário</span>
                    <span class="conteudo"><?php echo $cedente ?></span>
                </td>
                <td colspan="2">
                    <span class="titulo">CPF/CNPJ do Beneficiário</span>
                    <span class="conteudo"><?php echo $cedente_cpf_cnpj ?></span>
                </td>
                <td class="caixa-gray-bg">
                    <span class="titulo">Valor do Documento</span>
                    <span class="conteudo direita"><?php echo $valor_documento ?></span>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <span class="titulo">Endereço do Beneficiário</span>
                    <span class="conteudo"><?php echo $cedente_endereco1 ?> | <?php echo $cedente_endereco2 ?></span>
                </td>
                <td>
                    <span class="titulo">(-) Descontos / Abatimentos</span>
                    <span class="conteudo direita"><?php echo $desconto_abatimento ?></span>
                </td>
            </tr>
            <tr>
                <td colspan="4" rowspan="3" class="vtop">
                    <span class="titulo"><b>Demonstrativo</b></span>
                    <span class="conteudo margem-t10"><?php echo $demonstrativo[0] ?></span>
                    <span class="conteudo"><?php echo $demonstrativo[1] ?></span>
                    <span class="conteudo"><?php echo $demonstrativo[2] ?></span>
                    <span class="conteudo"><?php echo $demonstrativo[3] ?></span>
                    <span class="conteudo margem-b10"><?php echo $demonstrativo[4] ?></span>
                </td>
                <td>
                    <span class="titulo">(-) Outras deduções</span>
                    <span class="conteudo direita"><?php echo $outras_deducoes ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(+) Outros acréscimos</span>
                    <span class="conteudo direita"><?php echo $outros_acrescimos ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(=) Valor cobrado</span>
                    <span class="conteudo direita"><?php echo $valor_cobrado ?></span>
                </td>
            </tr>
            <tr>
                <td colspan="3" class="bottomborder">
                    <b>SAC CAIXA</b>: 0800 726 0101 (informações, reclamações, sugestões e elogios) <br />
                    <b>Para pessoas com deficiência auditiva ou de fala</b>: 0800 726 2492 <br />
                    <b>Ouvidoria</b>: 0800 725 7474 <br />
                    <b>caixa.gov.br</b>
                </td>
                <td colspan="2" class="bottomborder vtop">
                    <span class="titulo centro">Autenticação Mecânica - <b>Recibo do Pagador</b></span>
                    <span class="conteudo"></span>
                </td>
            </tr>
            </tbody>
        </table>

        <br />
        <div class="linha-pontilhada">Corte na linha pontilhada</div>
        <br />

        <!-- Ficha de compensação -->
        <?php include('partials/ficha-de-compensacao.phtml') ?>
    </div>
</body>
</html>
