<!DOCTYPE html>
<!--
* OpenBoleto - Geração de boletos bancários em PHP
*
* LICENSE: The MIT License (MIT)
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this
* software and associated documentation files (the "Software"), to deal in the Software
* without restriction, including without limitation the rights to use, copy, modify,
* merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to the following
* conditions:
*
* The above copyright notice and this permission notice shall be included in all copies
* or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
* PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <title><?php echo $cedente; ?></title>
        <style type="text/css">
            /* Embed the CSS content here */
            <?php include $resource_path . '/css/styles-pdf.css' ?>
        </style>
    </head>
    <body>

        <div>
            <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    <tr>
                        <td valign="bottom" colspan="5" class="noborder nopadding">
                            <div class="logocontainer">
                                <div class="logobanco">
                                    <img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
                                </div>
                                <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                            </div>
                            <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" width="225">
                            <div class="titulo">Beneficiário</div>
                            <div class="conteudo"><?php echo $cedente ?></div>
                        </td>
                        <td width="60" >
                            <div class="titulo">CNPJ/CPF</div>
                            <div class="conteudo"><?php echo $cedente_cpf_cnpj ?></div>
                        </td>

                        <td width="90" colspan="2">
                            <div class="titulo">Sacador Avalista</div>
                            <div class="conteudo rtl"></div>
                        </td>
                        <td width="200">
                            <div class="titulo">Vencimento</div>
                            <div class="conteudo rtl"><?php echo $data_vencimento ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <div class="titulo" >Endereço Beneficiário/Sacador Avalista</div>
                            <div class="conteudo lft"><?php echo $cedente_endereco1." ".$cedente_endereco2 ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            <div class="titulo">Nosso Número</div>
                            <div class="conteudo"><?php echo $nosso_numero; ?></div>
                        </td>
                        <td>
                            <div class="titulo">Carteira</div>
                            <div class="conteudo"><?php echo $carteira; ?></div>
                        </td>
                        <td>
                            <div class="titulo">Espécie</div>
                            <div class="conteudo"><?php echo $especie; ?></div>

                        </td>
                        <td>
                            <div class="titulo">Quantidade</div>
                            <div class="conteudo rtl"><?php echo $quantidade ?></div>
                        </td>
                        <td>
                            <div class="titulo">Valor</div>
                            <div class="conteudo rtl"><?php echo $valor_unitario ?></div>
                        </td>
                        <td>
                            <div class="titulo">Agência/Código do Beneficiário</div>
                            <div class="conteudo rtl"><?php echo $agencia_codigo_cedente ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="titulo">Data de Documento</div>
                            <div class="conteudo rtl"><?php echo $data_documento; ?></div>
                        </td>
                        <td>
                            <div class="titulo">Numero do Documento</div>
                            <div class="conteudo rtl"><?php echo $numero_documento ?></div>
                        </td>
                        <td>
                            <div class="titulo">Espécie do Documento</div>
                            <div class="conteudo lft"><?php echo $especie_doc ?></div>
                        </td>
                        <td>
                            <div class="titulo">Aceite</div>
                            <div class="conteudo rtl"><?php echo $aceite ?></div>
                        </td>
                        <td>
                            <div class="titulo">Data de Processamento</div>
                            <div class="conteudo rtl"><?php echo $data_processamento ?></div>
                        </td>
                        <td>
                            <div class="titulo">Valor Documento</div>
                            <div class="conteudo rtl"><?php echo $valor_documento ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div class="titulo">Demonstrativo</div>
                            <div class="conteudo"><?php echo $demonstrativo[0] ?></div>
                        </td>
                        <td  colspan="2" >
                            <div class="titulo">Autenticação mecânica</div>
                            <div class="conteudo"></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4" class="notopborder"><div class="conteudo"><?php echo $demonstrativo[1] ?></div></td>
                        <td  colspan="2"  class="notopborder"><div class="conteudo"></div></td>
                    </tr>
                    <tr>
                        <td colspan="4" class="notopborder"><div class="conteudo"><?php echo $demonstrativo[2] ?></div></td>
                        <td  colspan="2"   class="notopborder"><div class="conteudo"></div></td>
                    </tr>
                    <tr>
                        <td colspan="4" class="notopborder"><div class="conteudo"><?php echo $demonstrativo[3] ?></div></td>
                        <td  colspan="2"   class="notopborder"><div class="conteudo"></div></td>
                    </tr>
                    <tr>
                        <td colspan="4" class="notopborder" style="border: 1px solid #000;"><div style="margin-bottom: 10px;" class="conteudo"><?php echo $demonstrativo[4] ?></div></td>
                        <td   colspan="2"  class="notopborder" style="border: 1px solid #000;"><div class="conteudo"></div></td>
                    </tr>
                </tbody>
            </table>
            <br>
            <div class="linha-pontilhada">Corte na linha pontilhada</div>
            <br>

            <!-- Ficha de compensação -->
            <?php include('partials/ficha-de-compensacao-pdf.phtml') ?>
        </div>
    </body>
</html>
