<div style="width: 0px;float:left;margin-top: <?php echo ($counter-1)*365;?>px;">
	<div style="float: left;width: 150px;">
		<div class="logobanco">
			<img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
		</div>
		<span class="header">Recibo do Sacado</span>
		<table class="table-boleto" style="width: 150px;"  cellpadding="0" cellspacing="0" border="0">

			<tr>
				<td>
					<div class="titulo">Vencimento</div>
					<div class="conteudo"><?php echo $data_vencimento ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">Agência/Código do Cedente</div>
					<div class="conteudo"><?php echo $agencia_codigo_cedente ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">Nosso número</div>
					<div class="conteudo"><?php echo $nosso_numero ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">Nº documento</div>
					<div class="conteudo"><?php echo $numero_documento ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">Espécie</div>
					<div class="conteudo"><?php echo $especie ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">Quantidade</div>
					<div class="conteudo"><?php echo $quantidade ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">(=) Valor Documento</div>
					<div class="conteudo"><?php echo $valor_documento ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">(-) Descontos / Abatimentos</div>
					<div class="conteudo"><?php echo $desconto_abatimento ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">(-) Outras deduções</div>
					<div class="conteudo"><?php echo $outras_deducoes ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">(+) Mora / Multa</div>
					<div class="conteudo"><?php echo $mora_multa ?></div>
				</td>
			</tr>
			<tr>
				<td>
					<div class="titulo">(+) Outros acréscimos</div>
					<div class="conteudo"><?php echo $outros_acrescimos ?></div>
				</td>
			</tr>
			<tr>
				<td class="bottomborder">
					<div class="titulo">(=) Valor cobrado</div>
					<div class="conteudo"><?php echo $valor_cobrado ?></div>
				</td>
			</tr>
		</table>

	</div>
	<div style="float: left; margin-left: 160px;width: 0px;">
		<!-- Ficha de compensação -->
		<?php include('partials/ficha-de-compensacao-pdf.phtml') ?>
	</div>
	<div style="clear: both"></div>
	<div class="linha-pontilhada" style="margin-bottom: 5px;font: 3px Arial"></div>
</div>