<?php
/**
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title><?= $cedente; ?></title>
    <style type="text/css">
        /* Embed the CSS content here */
        <?php include $resource_path . '/css/styles.css' ?>
    </style>
</head>
<body>

<div class="carne">
    <div class="canhoto">
        <table class="table-boleto" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <span class="titulo">Vencimento</span>
                    <span class="conteudo"><?= $data_vencimento ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Agência/Código do Cedente</span>
                    <span class="conteudo"><?= $agencia_codigo_cedente ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Nosso número</span>
                    <span class="conteudo"><?= $nosso_numero ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Nº documento</span>
                    <span class="conteudo"><?= $numero_documento ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Espécie</span>
                    <span class="conteudo"><?= $especie ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">Quantidade</span>
                    <span class="conteudo"><?= $quantidade ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(=) Valor Documento</span>
                    <span class="conteudo"><?= $valor_documento ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(-) Descontos / Abatimentos</span>
                    <span class="conteudo"><?= $desconto_abatimento ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(-) Outras deduções</span>
                    <span class="conteudo"><?= $outras_deducoes ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(+) Mora / Multa</span>
                    <span class="conteudo"><?= $mora_multa ?></span>
                </td>
            </tr>
            <tr>
                <td>
                    <span class="titulo">(+) Outros acréscimos</span>
                    <span class="conteudo"><?= $outros_acrescimos ?></span>
                </td>
            </tr>
            <tr>
                <td class="bottomborder">
                    <span class="titulo">(=) Valor cobrado</span>
                    <span class="conteudo"><?= $valor_cobrado ?></span>
                </td>
            </tr>
        </table>
        <span class="header">Recibo do Sacado</span>
    </div>
    <div class="ficha-cobranca">
        <!-- Ficha de compensação -->
        <?php include('partials/ficha-de-compensacao.phtml'); ?>
    </div>
    <div class="linha-pontilhada">Corte na linha pontilhada</div>
</div>

</body>
</html>
