<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<div class="boleto-header">
    <div class="leftcontainer">
        <img src="<?= $logo_banco; ?>" alt="logotipo do banco" />
        <span class="codbanco"><?= $codigo_banco_com_dv ?></span>
    </div>
    <div class="rightcontainer">
        <span class="linha-digitavel"><?= $linha_digitavel ?></span>
    </div>
</div>
<table class="table-boleto" cellpadding="0" cellspacing="0">
    <tbody>
    <tr>
        <td width="74%" colspan="7">
            <span class="titulo">Local de pagamento</span>
            <span class="conteudo"><?= $local_pagamento ?></span>
        </td>
        <td width="26%">
            <span class="titulo">Vencimento</span>
            <span class="conteudo direita"><?= $data_vencimento ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <span class="titulo">Beneficiário</span>
            <span class="conteudo"><?= $cedente ?></span>
        </td>
        <td>
            <span class="titulo">Agência/Código beneficiário</span>
            <span class="conteudo direita"><?= $agencia_codigo_cedente ?></span>
        </td>
    </tr>
    <tr>
        <td width="19%" colspan="2">
            <span class="titulo">Data do documento</span>
            <span class="conteudo"><?= $data_documento ?></span>
        </td>
        <td width="20%" colspan="2">
            <span class="titulo">Nº documento</span>
            <span class="conteudo"><?= $numero_documento ?></span>
        </td>
        <td width="10%">
            <span class="titulo">Espécie doc.</span>
            <span class="conteudo"><?= $especie_doc ?></span>
        </td>
        <td width="8%">
            <span class="titulo">Aceite</span>
            <span class="conteudo"><?= $aceite ?></span>
        </td>
        <td width="17%">
            <span class="titulo">Data processamento</span>
            <span class="conteudo"><?= $data_processamento ?></span>
        </td>
        <td width="26%">
            <span class="titulo">Nosso número</span>
            <span class="conteudo direita"><?= $nosso_numero ?></span>
        </td>
    </tr>
    <tr>
        <?php if (!$esconde_uso_banco) : ?>
            <td<?php if (!$mostra_cip) : ?> width="18%" colspan="2"<?php else: ?> width="10%"<?php endif ?>>
                <span class="titulo">Uso do banco</span>
                <span class="conteudo"><?= $uso_banco ?></span>
            </td>
        <?php endif; ?>

        <?php if ($mostra_cip) : ?>
            <!-- Campo exclusivo do Bradesco -->
            <td width="8%">
                <span class="titulo">CIP</span>
                <span class="conteudo"><?= $cip ?></span>
            </td>
        <?php endif ?>

        <td<?php if ($esconde_uso_banco) : ?> width="31%" colspan="3"<?php endif; ?>>
            <span class="titulo">Carteira</span>
            <span class="conteudo"><?= $carteira ?></span>
        </td>
        <td width="8%">
            <span class="titulo">Espécie</span>
            <span class="conteudo"><?= $especie ?></span>
        </td>
        <td width="18%" colspan="2">
            <span class="titulo">Quantidade</span>
            <span class="conteudo"><?= $quantidade ?></span>
        </td>
        <td width="17%">
            <span class="titulo">Valor</span>
            <span class="conteudo"><?= $valor_unitario ?></span>
        </td>
        <td width="26%">
            <span class="titulo">(=) Valor do Documento</span>
            <span class="conteudo direita"><?= $valor_documento ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <span class="titulo">Instruções (Texto de responsabilidade do beneficiário)</span>
        </td>
        <td>
            <span class="titulo">(-) Descontos / Abatimentos</span>
            <span class="conteudo direita"><?= $desconto_abatimento ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="notopborder">
            <span class="conteudo"><?= $instrucoes[0]; ?></span>
            <span class="conteudo"><?= $instrucoes[1]; ?></span>
        </td>
        <td>
            <span class="titulo">(-) Outras deduções</span>
            <span class="conteudo direita"><?= $outras_deducoes ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="notopborder">
            <span class="conteudo"><?= $instrucoes[2]; ?></span>
            <span class="conteudo"><?= $instrucoes[3]; ?></span>
        </td>
        <td>
            <span class="titulo">(+) Mora / Multa</span>
            <span class="conteudo direita"><?= $mora_multa ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="notopborder">
            <span class="conteudo"><?= $instrucoes[4]; ?></span>
            <span class="conteudo"><?= $instrucoes[5]; ?></span>
        </td>
        <td>
            <span class="titulo">(+) Outros acréscimos</span>
            <span class="conteudo direita"><?= $outros_acrescimos ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7" class="notopborder">
            <span class="conteudo"><?= $instrucoes[6]; ?></span>
            <span class="conteudo"><?= $instrucoes[7]; ?></span>
        </td>
        <td>
            <span class="titulo">(=) Valor cobrado</span>
            <span class="conteudo direita"><?= $valor_cobrado ?></span>
        </td>
    </tr>
    <tr>
        <td colspan="7">
            <span class="titulo">Pagador</span>
            <span class="conteudo"><?= $sacado ?></span>
            <span class="conteudo"><?= $sacado_endereco1 ?></span>
            <span class="conteudo"><?= $sacado_endereco2 ?></span>

        </td>
        <td class="noleftborder">
            <span class="titulo margem-t50">Cód. Baixa</span>
        </td>
    </tr>

    <tr>
        <td colspan="6" class="noleftborder">
            <span class="titulo">Sacador/Avalista: <b class="conteudo sacador"><?= $sacador_avalista; ?></b></span>
        </td>
        <td colspan="2" class="norightborder noleftborder">
            <span class="conteudo noborder direita">Autenticação mecânica - Ficha de Compensação</span>
        </td>
    </tr>

    <tr>
        <td colspan="8" class="noborder">
            <?= $codigo_barras ?>
        </td>
    </tr>

    </tbody>
</table>
